import Mathlib

open Polynomial Filter Topology

abbrev putnam_1976_b2_solution : ℕ × Set (List (ℤ × ℤ)) :=
(8, (Set.range (fun j : Fin 7 => [((0 : ℤ), ((j : ℕ) : ℤ))]) ∪
      { [((2 : ℤ), (0 : ℤ))] }))

/--
Let $G$ be a group generated by two elements $A$ and $B$; i.e., every element of $G$ can be expressed as a finite word $A^{n_1}B^{n_2} \cdots A^{n_{k-1}}B^{n_k}$, where the $n_i$ can assume any integer values and $A^0 = B^0 = 1$. Further assume that $A^4 = B^7 = ABA^{-1}B = 1$, but $A^2 \ne 1$ and $B \ne 1$. Find the number of elements of $G$ than can be written as $C^2$ for some $C \in G$ and express each such square as a word in $A$ and $B$.
-/
theorem putnam_1976_b2
(G : Type*) [Group G]
(A B : G)
(word : List (ℤ × ℤ) → G)
(hword : word = fun w : List (ℤ × ℤ) => (List.map (fun t : ℤ × ℤ => A^(t.1)*B^(t.2)) w).prod)
(hG : ∀ g : G, ∃ w : List (ℤ × ℤ), g = word w)
(hA : A^4 = 1 ∧ A^2 ≠ 1)
(hB : B^7 = 1 ∧ B ≠ 1)
(h1 : A*B*A^(-(1 : ℤ))*B = 1)
(S : Set G)
(hS : S = {g : G | ∃ C : G, C^2 = g})
: S.ncard = putnam_1976_b2_solution.1 ∧ S = {word w | w ∈ putnam_1976_b2_solution.2} :=
by
  classical
  let T : Set G := insert (A^2) (Set.range (fun j : Fin 7 => B^((j : ℕ) : ℤ)))
  have hA4z : A ^ (4 : ℤ) = 1 := by exact_mod_cast hA.1
  have hBord : orderOf B = 7 := by
    haveI : Fact (Nat.Prime 7) := ⟨by norm_num⟩
    exact orderOf_eq_prime hB.1 hB.2
  have hconj : A * B * A⁻¹ = B⁻¹ := by
    have h1' : A * B * A⁻¹ * B = 1 := by simpa using h1
    calc
      A * B * A⁻¹ = (A * B * A⁻¹ * B) * B⁻¹ := by group
      _ = 1 * B⁻¹ := by rw [h1']
      _ = B⁻¹ := by simp
  have hconj_z : ∀ j : ℤ, A * B^j * A⁻¹ = B^(-j) := by
    intro j
    calc
      A * B^j * A⁻¹ = (A * B * A⁻¹)^j := by rw [conj_zpow]
      _ = (B⁻¹)^j := by rw [hconj]
      _ = B^(-j) := by rw [inv_zpow']
  have hmoveBA : ∀ j : ℤ, B^j * A = A * B^(-j) := by
    intro j
    have h := hconj_z (-j)
    calc
      B^j * A = (A * B^(-j) * A⁻¹) * A := by
        rw [h]
        simp
      _ = A * B^(-j) := by group
  have hAB : A * B = B⁻¹ * A := by
    calc
      A * B = (A * B * A⁻¹) * A := by group
      _ = B⁻¹ * A := by rw [hconj]
  have hBA : B * A = A * B⁻¹ := by
    simpa using hmoveBA 1
  have hA2B : A^2 * B = B * A^2 := by
    calc
      A^2 * B = A * (A * B) := by rw [pow_two]; group
      _ = A * (B⁻¹ * A) := by rw [hAB]
      _ = (A * B⁻¹) * A := by group
      _ = (B * A) * A := by rw [hBA.symm]
      _ = B * A^2 := by rw [pow_two]; group
  have hcommA2B : Commute (A^2) B := by
    rw [commute_iff_eq]
    exact hA2B
  have hA2z : A ^ (2 : ℤ) = A ^ (2 : ℕ) := by
    change A ^ ((2 : ℕ) : ℤ) = A ^ (2 : ℕ)
    rw [zpow_natCast]
  have hcommA2Bz : Commute (A^(2 : ℤ)) B := by
    simpa [hA2z] using hcommA2B
  have hmove_even : ∀ k j : ℤ, B^j * A^(2*k) = A^(2*k) * B^j := by
    intro k j
    have hcomm : Commute (A^(2*k)) (B^j) := by
      simpa [zpow_mul] using hcommA2Bz.zpow_zpow k j
    exact hcomm.eq.symm
  have hmove_odd : ∀ k j : ℤ, B^j * A^(2*k + 1) = A^(2*k + 1) * B^(-j) := by
    intro k j
    have hAodd : A^(2*k + 1) = A^(2*k) * A := by
      rw [zpow_add]
      simp
    calc
      B^j * A^(2*k + 1) = B^j * (A^(2*k) * A) := by rw [hAodd]
      _ = (B^j * A^(2*k)) * A := by group
      _ = (A^(2*k) * B^j) * A := by rw [hmove_even]
      _ = A^(2*k) * (B^j * A) := by group
      _ = A^(2*k) * (A * B^(-j)) := by rw [hmoveBA]
      _ = (A^(2*k) * A) * B^(-j) := by group
      _ = A^(2*k + 1) * B^(-j) := by rw [hAodd]
  have hmul_nf : ∀ a b i j : ℤ, ∃ i' j' : ℤ, (A^a*B^b)*(A^i*B^j) = A^i' * B^j' := by
    intro a b i j
    rcases Int.even_or_odd' i with ⟨k, hk | hk⟩
    · subst i
      refine ⟨a + 2*k, b + j, ?_⟩
      calc
        (A^a * B^b) * (A^(2*k) * B^j) = A^a * (B^b * A^(2*k)) * B^j := by group
        _ = A^a * (A^(2*k) * B^b) * B^j := by rw [hmove_even]
        _ = (A^a * A^(2*k)) * (B^b * B^j) := by group
        _ = A^(a + 2*k) * B^(b + j) := by rw [← zpow_add, ← zpow_add]
    · subst i
      refine ⟨a + (2*k + 1), -b + j, ?_⟩
      calc
        (A^a * B^b) * (A^(2*k + 1) * B^j) = A^a * (B^b * A^(2*k + 1)) * B^j := by group
        _ = A^a * (A^(2*k + 1) * B^(-b)) * B^j := by rw [hmove_odd]
        _ = (A^a * A^(2*k + 1)) * (B^(-b) * B^j) := by group
        _ = A^(a + (2*k + 1)) * B^(-b + j) := by rw [← zpow_add, ← zpow_add]
  have hword_nf : ∀ w, ∃ i j : ℤ, word w = A^i * B^j := by
    have hprod_nf : ∀ w : List (ℤ × ℤ), ∃ i j : ℤ,
        (List.map (fun t : ℤ × ℤ => A^(t.1)*B^(t.2)) w).prod = A^i * B^j := by
      intro w
      induction w with
      | nil =>
          refine ⟨0, 0, ?_⟩
          simp
      | cons t w ih =>
          rcases t with ⟨a, b⟩
          rcases ih with ⟨i, j, hij⟩
          rcases hmul_nf a b i j with ⟨i', j', hmul⟩
          refine ⟨i', j', ?_⟩
          simp only [List.map_cons, List.prod_cons]
          rw [hij]
          exact hmul
    intro w
    rcases hprod_nf w with ⟨i, j, hij⟩
    exact ⟨i, j, by rw [hword]; exact hij⟩
  have hB_reduce : ∀ n : ℤ, ∃ r : Fin 7, B^n = B^((r : ℕ) : ℤ) := by
    intro n
    let rint : ℤ := n % 7
    have hrnonneg : 0 ≤ rint := Int.emod_nonneg n (by norm_num)
    have hrlt : rint < 7 := Int.emod_lt_of_pos n (by norm_num)
    let rnat : ℕ := rint.toNat
    have hrnatlt : rnat < 7 := (Int.toNat_lt hrnonneg).2 hrlt
    refine ⟨⟨rnat, hrnatlt⟩, ?_⟩
    have hcast : ((rnat : ℕ) : ℤ) = rint := Int.toNat_of_nonneg hrnonneg
    rw [zpow_eq_zpow_iff_modEq, hBord]
    rw [hcast]
    exact (Int.mod_modEq n 7).symm
  have hAz4 : ∀ k : ℤ, A ^ (4 * k) = 1 := by
    intro k
    calc
      A ^ (4 * k) = (A ^ (4 : ℤ)) ^ k := by rw [zpow_mul]
      _ = 1 ^ k := by rw [hA4z]
      _ = 1 := by simp
  have hsquare_even : ∀ k j : ℤ, (A^(2*k) * B^j)^2 = B^(2*j) := by
    intro k j
    have hcomm : Commute (A^(2*k)) (B^j) := by
      rw [commute_iff_eq]
      exact (hmove_even k j).symm
    calc
      (A ^ (2 * k) * B ^ j)^2 = (A ^ (2 * k))^2 * (B ^ j)^2 := by rw [hcomm.mul_pow]
      _ = A ^ ((2 * k) * (2 : ℤ)) * B ^ (j * (2 : ℤ)) := by simp [← zpow_natCast, zpow_mul]
      _ = A ^ (4 * k) * B ^ (2 * j) := by ring_nf
      _ = 1 * B ^ (2 * j) := by rw [hAz4]
      _ = B ^ (2 * j) := by simp
  have hsquare_odd : ∀ k j : ℤ, (A^(2*k + 1) * B^j)^2 = A^2 := by
    intro k j
    calc
      (A^(2*k + 1) * B^j)^2 = A^(2*k + 1) * (B^j * A^(2*k + 1)) * B^j := by rw [pow_two]; group
      _ = A^(2*k + 1) * (A^(2*k + 1) * B^(-j)) * B^j := by rw [hmove_odd]
      _ = (A^(2*k + 1) * A^(2*k + 1)) * (B^(-j) * B^j) := by group
      _ = A^((2*k + 1) + (2*k + 1)) := by rw [← zpow_add]; simp
      _ = A^(4*k + 2) := by ring_nf
      _ = A^(4*k) * A^(2 : ℤ) := by rw [← zpow_add]
      _ = 1 * A^(2 : ℤ) := by rw [hAz4]
      _ = A^(2 : ℤ) := by simp
      _ = A^2 := by
        change A ^ ((2 : ℕ) : ℤ) = A ^ (2 : ℕ)
        rw [zpow_natCast]
  have hsquare_mem_T : ∀ i j : ℤ, (A^i * B^j)^2 ∈ T := by
    intro i j
    rcases Int.even_or_odd' i with ⟨k, hk | hk⟩
    · subst i
      rw [hsquare_even k j]
      rcases hB_reduce (2*j) with ⟨r, hr⟩
      exact Or.inr ⟨r, hr.symm⟩
    · subst i
      rw [hsquare_odd k j]
      exact Or.inl rfl
  have hsquareB : ∀ r : Fin 7, ∃ C : G, C^2 = B^((r : ℕ) : ℤ) := by
    intro r
    let m : ℤ := ((4 * (r : ℕ) : ℕ) : ℤ)
    refine ⟨B^m, ?_⟩
    calc
      (B^m)^2 = B^(m * (2 : ℤ)) := by simp [← zpow_natCast, zpow_mul]
      _ = B^(((r : ℕ) : ℤ)) := by
        rw [zpow_eq_zpow_iff_modEq, hBord]
        rw [Int.modEq_iff_dvd]
        use -((r : ℕ) : ℤ)
        dsimp [m]
        ring
  have hS_T : S = T := by
    rw [hS]
    ext g
    constructor
    · rintro ⟨C, hCg⟩
      rcases hG C with ⟨w, hw⟩
      rcases hword_nf w with ⟨i, j, hw_nf⟩
      rw [← hCg, hw, hw_nf]
      exact hsquare_mem_T i j
    · intro hg
      rcases hg with hgA | ⟨r, hgr⟩
      · refine ⟨A, ?_⟩
        rw [hgA]
      · rcases hsquareB r with ⟨C, hC⟩
        refine ⟨C, ?_⟩
        rw [← hgr]
        exact hC
  have hBpow7 : ∀ n : ℤ, (B^n)^7 = 1 := by
    intro n
    have hB7z : B ^ (7 : ℤ) = 1 := by exact_mod_cast hB.1
    calc
      (B^n)^7 = B^(n * (7 : ℤ)) := by simp [← zpow_natCast, zpow_mul]
      _ = B^((7 : ℤ) * n) := by rw [mul_comm]
      _ = (B^(7 : ℤ))^n := by rw [zpow_mul]
      _ = 1^n := by rw [hB7z]
      _ = 1 := by simp
  have hA2pow7 : (A^2)^7 = A^2 := by
    have hA2sq : (A^2)^2 = 1 := by
      rw [← pow_mul]
      norm_num
      exact hA.1
    calc
      (A^2)^7 = ((A^2)^2)^3 * A^2 := by group
      _ = 1^3 * A^2 := by rw [hA2sq]
      _ = A^2 := by simp
  have hnotA2_range : A^2 ∉ Set.range (fun j : Fin 7 => B^((j : ℕ) : ℤ)) := by
    rintro ⟨r, hr⟩
    have hA2eq1 : A^2 = 1 := by
      calc
        A^2 = (A^2)^7 := by rw [hA2pow7]
        _ = (B^((r : ℕ) : ℤ))^7 := by rw [← hr]
        _ = 1 := hBpow7 ((r : ℕ) : ℤ)
    exact hA.2 hA2eq1
  have hinjB : Function.Injective (fun r : Fin 7 => B^((r : ℕ) : ℤ)) := by
    intro r s h
    apply Fin.ext
    have hmod' : ((r : ℕ) : ℤ) ≡ ((s : ℕ) : ℤ) [ZMOD ((orderOf B : ℕ) : ℤ)] :=
      zpow_eq_zpow_iff_modEq.mp h
    have hmod : ((r : ℕ) : ℤ) ≡ ((s : ℕ) : ℤ) [ZMOD (7 : ℤ)] := by
      simpa [hBord] using hmod'
    rw [Int.modEq_iff_dvd] at hmod
    rcases hmod with ⟨k, hk⟩
    have hvals : ((r : ℕ) : ℤ) = ((s : ℕ) : ℤ) := by omega
    exact_mod_cast hvals
  have hTcard : T.ncard = 8 := by
    calc
      T.ncard = (Set.range (fun j : Fin 7 => B^((j : ℕ) : ℤ))).ncard + 1 := by
        dsimp [T]
        rw [Set.ncard_insert_of_notMem hnotA2_range]
      _ = 7 + 1 := by
        rw [Set.ncard_range_of_injective hinjB]
        simp
      _ = 8 := by norm_num
  have hwordA2 : word [((2 : ℤ), (0 : ℤ))] = A^2 := by
    rw [hword]
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one]
    change A ^ ((2 : ℕ) : ℤ) * B ^ (0 : ℤ) = A ^ (2 : ℕ)
    rw [zpow_natCast]
    simp
  have hwordBz : ∀ j : ℤ, word [((0 : ℤ), j)] = B^j := by
    intro j
    rw [hword]
    simp
  have hwordNil : word [] = 1 := by
    rw [hword]
    simp
  have hwordB : ∀ j : Fin 7, word [((0 : ℤ), ((j : ℕ) : ℤ))] = B^((j : ℕ) : ℤ) := by
    intro j
    simpa using hwordBz ((j : ℕ) : ℤ)
  have hwordB0 : word [((0 : ℤ), (0 : ℤ))] = B^(0 : ℤ) := by
    simpa using hwordB ⟨0, by norm_num⟩
  have hwordB1 : word [((0 : ℤ), (1 : ℤ))] = B^(1 : ℤ) := by
    simpa using hwordB ⟨1, by norm_num⟩
  have hwordB2 : word [((0 : ℤ), (2 : ℤ))] = B^(2 : ℤ) := by
    simpa using hwordB ⟨2, by norm_num⟩
  have hwordB3 : word [((0 : ℤ), (3 : ℤ))] = B^(3 : ℤ) := by
    simpa using hwordB ⟨3, by norm_num⟩
  have hwordB4 : word [((0 : ℤ), (4 : ℤ))] = B^(4 : ℤ) := by
    simpa using hwordB ⟨4, by norm_num⟩
  have hwordB5 : word [((0 : ℤ), (5 : ℤ))] = B^(5 : ℤ) := by
    simpa using hwordB ⟨5, by norm_num⟩
  have hwordB6 : word [((0 : ℤ), (6 : ℤ))] = B^(6 : ℤ) := by
    simpa using hwordB ⟨6, by norm_num⟩
  have hWT : {word w | w ∈ putnam_1976_b2_solution.2} = T := by
    ext g
    constructor
    · rintro ⟨w, hw, hgw⟩
      change w ∈ (Set.range (fun j : Fin 7 => [((0 : ℤ), ((j : ℕ) : ℤ))]) ∪
        { [((2 : ℤ), (0 : ℤ))] } : Set (List (ℤ × ℤ))) at hw
      rw [Set.mem_union, Set.mem_singleton_iff] at hw
      rcases hw with ⟨j, rfl⟩ | rfl
      · rw [← hgw, hwordB j]
        exact Or.inr ⟨j, rfl⟩
      · rw [← hgw, hwordA2]
        exact Or.inl rfl
    · intro hg
      change g = A^2 ∨ g ∈ Set.range (fun j : Fin 7 => B^((j : ℕ) : ℤ)) at hg
      rcases hg with rfl | ⟨j, rfl⟩
      · refine ⟨[((2 : ℤ), (0 : ℤ))], ?_, hwordA2⟩
        change [((2 : ℤ), (0 : ℤ))] ∈
          (Set.range (fun j : Fin 7 => [((0 : ℤ), ((j : ℕ) : ℤ))]) ∪
          { [((2 : ℤ), (0 : ℤ))] } : Set (List (ℤ × ℤ)))
        exact Or.inr rfl
      · refine ⟨[((0 : ℤ), ((j : ℕ) : ℤ))], ?_, hwordB j⟩
        change [((0 : ℤ), ((j : ℕ) : ℤ))] ∈
          (Set.range (fun j : Fin 7 => [((0 : ℤ), ((j : ℕ) : ℤ))]) ∪
          { [((2 : ℤ), (0 : ℤ))] } : Set (List (ℤ × ℤ)))
        exact Or.inl ⟨j, rfl⟩
  constructor
  · change S.ncard = 8
    rw [hS_T]
    exact hTcard
  · rw [hS_T, hWT]
