import Mathlib

open Polynomial Filter Topology

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false

-- (8, {[(0, 0)], [(2, 0)], [(0, 1)], [(0, 2)], [(0, 3)], [(0, 4)], [(0, 5)], [(0, 6)]})
/--
Let $G$ be a group generated by two elements $A$ and $B$; i.e., every element of $G$ can be expressed as a finite word $A^{n_1}B^{n_2} \cdots A^{n_{k-1}}B^{n_k}$, where the $n_i$ can assume any integer values and $A^0 = B^0 = 1$. Further assume that $A^4 = B^7 = ABA^{-1}B = 1$, but $A^2 \ne 1$ and $B \ne 1$. Find the number of elements of $G$ than can be written as $C^2$ for some $C \in G$ and express each such square as a word in $A$ and $B$.
-/
theorem putnam_1976_b2
(G : Type*) [Group G]
(A B : G)
(word : List (ℤ × ℤ) → G)
(hword : word = fun w : List (ℤ × ℤ) => (List.map (fun t : ℤ × ℤ => A^(t.1)*B^(t.2)) w).prod)
(hG : ∀ g : G, ∃ w : List (ℤ × ℤ), g = word w)
(hA : A^4 = 1 ∧ A^2 ≠ 1)
(hB : B^7 = 1 ∧ B ≠ 1)
(h1 : A*B*A^(-(1 : ℤ))*B = 1)
(S : Set G)
(hS : S = {g : G | ∃ C : G, C^2 = g})
: S.ncard = ((8, {[(0, 0)], [(2, 0)], [(0, 1)], [(0, 2)], [(0, 3)], [(0, 4)], [(0, 5)], [(0, 6)]}) : ℕ × Set (List (ℤ × ℤ)) ).1 ∧ S = {word w | w ∈ ((8, {[(0, 0)], [(2, 0)], [(0, 1)], [(0, 2)], [(0, 3)], [(0, 4)], [(0, 5)], [(0, 6)]}) : ℕ × Set (List (ℤ × ℤ)) ).2} := by
  classical
  let L : Set (List (ℤ × ℤ)) :=
    {[(0, 0)], [(2, 0)], [(0, 1)], [(0, 2)], [(0, 3)], [(0, 4)], [(0, 5)], [(0, 6)]}
  let T : Set G := {word w | w ∈ L}
  change S.ncard = 8 ∧ S = T
  have hAo_dvd : orderOf A ∣ 4 := by
    exact orderOf_dvd_of_pow_eq_one (x := A) (n := 4) hA.1
  have hAo_le : orderOf A ≤ 4 := Nat.le_of_dvd (by norm_num) hAo_dvd
  have hAo : orderOf A = 4 := by
    interval_cases h : orderOf A
    · norm_num at hAo_dvd
    · have hA1 : A = 1 := orderOf_eq_one_iff.mp h
      exact False.elim (hA.2 (by simp [hA1]))
    · have hA2 : A ^ 2 = 1 := by simpa [h] using pow_orderOf_eq_one A
      exact False.elim (hA.2 hA2)
    · norm_num [h] at hAo_dvd
    · rfl
  haveI : Fact (Nat.Prime 7) := ⟨by norm_num⟩
  have hBo : orderOf B = 7 := by
    exact orderOf_eq_prime hB.1 hB.2
  have hconj : A * B * A⁻¹ = B⁻¹ := by
    have hh : A * B * A⁻¹ * B = 1 := by simpa using h1
    exact eq_inv_of_mul_eq_one_left hh
  have hconj_zpow : ∀ n : ℤ, A * B^n * A⁻¹ = B^(-n) := by
    intro n
    have hsmul : ConjAct.toConjAct A • B = B⁻¹ := by
      simpa [ConjAct.toConjAct_smul] using hconj
    calc
      A * B^n * A⁻¹ = ConjAct.toConjAct A • (B^n) := by
        simp [ConjAct.toConjAct_smul]
      _ = (ConjAct.toConjAct A • B)^n := by
        rw [smul_zpow']
      _ = (B⁻¹)^n := by rw [hsmul]
      _ = B^(-n) := by rw [inv_zpow']
  have hBA : ∀ n : ℤ, B^n * A = A * B^(-n) := by
    intro n
    have h := hconj_zpow (-n)
    have h' := congr_arg (fun x => x * A) h
    simpa [mul_assoc] using h'.symm
  have hmove : ∀ y m : ℤ, ∃ z : ℤ, B^y * A^m = A^m * B^z := by
    intro y m
    have hm : A ^ (m % (4 : ℤ)) = A^m := by
      simpa [hAo] using zpow_mod_orderOf A m
    have hnonneg : 0 ≤ m % (4 : ℤ) := Int.emod_nonneg _ (by norm_num)
    have hlt : m % (4 : ℤ) < 4 := Int.emod_lt_of_pos _ (by norm_num)
    interval_cases hr : m % (4 : ℤ)
    · refine ⟨y, ?_⟩
      simp [← hm]
    · refine ⟨-y, ?_⟩
      simpa [← hm] using hBA y
    · refine ⟨y, ?_⟩
      calc
        B^y * A^m = B^y * A^(2 : ℤ) := by rw [← hm]
        _ = (B^y * A) * A := by rw [zpow_two, mul_assoc]
        _ = (A * B^(-y)) * A := by rw [hBA]
        _ = A * (B^(-y) * A) := by rw [mul_assoc]
        _ = A * (A * B^(-(-y))) := by rw [hBA]
        _ = A^m * B^y := by rw [neg_neg, ← mul_assoc, ← zpow_two, hm]
    · refine ⟨-y, ?_⟩
      have hz3 : A^(3 : ℤ) = (A * A) * A := by
        rw [show (3 : ℤ) = ((3 : ℕ) : ℤ) from rfl, zpow_natCast]
        rw [show (3 : ℕ) = 2 + 1 from rfl, pow_succ, pow_two]
      calc
        B^y * A^m = B^y * A^(3 : ℤ) := by rw [← hm]
        _ = B^y * ((A * A) * A) := by rw [hz3]
        _ = ((B^y * A) * A) * A := by simp [mul_assoc]
        _ = ((A * B^(-y)) * A) * A := by rw [hBA]
        _ = (A * (B^(-y) * A)) * A := by rw [mul_assoc A (B^(-y)) A]
        _ = (A * (A * B^(-(-y)))) * A := by rw [hBA]
        _ = (A * (A * B^y)) * A := by rw [neg_neg]
        _ = (A * A) * (B^y * A) := by simp [mul_assoc]
        _ = (A * A) * (A * B^(-y)) := by rw [hBA]
        _ = A^m * B^(-y) := by rw [← mul_assoc, ← hz3, hm]
  have hnf_word : ∀ w : List (ℤ × ℤ), ∃ i j : ℤ, word w = A^i * B^j := by
    intro w
    rw [hword]
    induction w with
    | nil =>
        refine ⟨0, 0, ?_⟩
        simp
    | cons t ts ih =>
        obtain ⟨i, j, hij⟩ := ih
        have hij' : (List.map (fun t : ℤ × ℤ => A ^ t.1 * B ^ t.2) ts).prod = A ^ i * B ^ j := by
          simpa using hij
        obtain ⟨z, hz⟩ := hmove t.2 i
        refine ⟨t.1 + i, z + j, ?_⟩
        simp only [List.map_cons, List.prod_cons]
        calc
          (A ^ t.1 * B ^ t.2) * (List.map (fun t : ℤ × ℤ => A ^ t.1 * B ^ t.2) ts).prod
              = (A ^ t.1 * B ^ t.2) * (A ^ i * B ^ j) := by rw [hij']
          _ = A ^ t.1 * (B ^ t.2 * A ^ i) * B ^ j := by simp [mul_assoc]
          _ = A ^ t.1 * (A ^ i * B ^ z) * B ^ j := by rw [hz]
          _ = A ^ (t.1 + i) * B ^ (z + j) := by rw [zpow_add, zpow_add]; simp [mul_assoc]
  have hBA2 : ∀ y : ℤ, B^y * A^(2 : ℤ) = A^(2 : ℤ) * B^y := by
    intro y
    calc
      B^y * A^(2 : ℤ) = (B^y * A) * A := by rw [zpow_two, mul_assoc]
      _ = (A * B^(-y)) * A := by rw [hBA]
      _ = A * (B^(-y) * A) := by rw [mul_assoc]
      _ = A * (A * B^(-(-y))) := by rw [hBA]
      _ = A^(2 : ℤ) * B^y := by rw [neg_neg, ← mul_assoc, ← zpow_two]
  have hBA3 : ∀ y : ℤ, B^y * A^(3 : ℤ) = A^(3 : ℤ) * B^(-y) := by
    intro y
    have hz3 : A^(3 : ℤ) = (A * A) * A := by
      rw [show (3 : ℤ) = ((3 : ℕ) : ℤ) from rfl, zpow_natCast]
      rw [show (3 : ℕ) = 2 + 1 from rfl, pow_succ, pow_two]
    calc
      B^y * A^(3 : ℤ) = B^y * ((A * A) * A) := by rw [hz3]
      _ = ((B^y * A) * A) * A := by simp [mul_assoc]
      _ = ((A * B^(-y)) * A) * A := by rw [hBA]
      _ = (A * (B^(-y) * A)) * A := by rw [mul_assoc A (B^(-y)) A]
      _ = (A * (A * B^(-(-y)))) * A := by rw [hBA]
      _ = (A * (A * B^y)) * A := by rw [neg_neg]
      _ = (A * A) * (B^y * A) := by simp [mul_assoc]
      _ = (A * A) * (A * B^(-y)) := by rw [hBA]
      _ = A^(3 : ℤ) * B^(-y) := by rw [← mul_assoc, ← hz3]
  have hA62 : A^(6 : ℤ) = A^(2 : ℤ) := by
    rw [zpow_eq_zpow_iff_modEq, hAo]
    norm_num [Int.ModEq]
  have hsqB : ∀ j : ℤ, (B^j)^2 = B^(2*j) := by
    intro j
    calc
      (B^j)^2 = B^j * B^j := by rw [pow_two]
      _ = B^(j+j) := by rw [zpow_add]
      _ = B^(2*j) := by ring_nf
  have hsqA1 : ∀ j : ℤ, (A * B^j)^2 = A^(2 : ℤ) := by
    intro j
    calc
      (A * B^j)^2 = A * B^j * (A * B^j) := by rw [pow_two]
      _ = A * (B^j * A) * B^j := by simp [mul_assoc]
      _ = A * (A * B^(-j)) * B^j := by rw [hBA]
      _ = A * A * (B^(-j) * B^j) := by simp [mul_assoc]
      _ = A * A * B^((-j) + j) := by rw [zpow_add]
      _ = A^(2 : ℤ) := by rw [neg_add_cancel, zpow_zero, mul_one, ← zpow_two]
  have hsqA2 : ∀ j : ℤ, (A^(2 : ℤ) * B^j)^2 = B^(2*j) := by
    intro j
    calc
      (A^(2 : ℤ) * B^j)^2 = A^(2 : ℤ) * B^j * (A^(2 : ℤ) * B^j) := by rw [pow_two]
      _ = A^(2 : ℤ) * (B^j * A^(2 : ℤ)) * B^j := by simp [mul_assoc]
      _ = A^(2 : ℤ) * (A^(2 : ℤ) * B^j) * B^j := by rw [hBA2]
      _ = (A^(2 : ℤ) * A^(2 : ℤ)) * (B^j * B^j) := by simp [mul_assoc]
      _ = A^((2 : ℤ) + 2) * B^(j+j) := by rw [zpow_add, zpow_add]
      _ = 1 * B^(2*j) := by
        have hA4 : A^((2 : ℤ) + 2) = 1 := by
          change A^(4 : ℤ) = 1
          rw [zpow_eq_one_iff_modEq, hAo]
          norm_num [Int.ModEq]
        rw [hA4]
        ring_nf
      _ = B^(2*j) := by simp
  have hsqA3 : ∀ j : ℤ, (A^(3 : ℤ) * B^j)^2 = A^(2 : ℤ) := by
    intro j
    calc
      (A^(3 : ℤ) * B^j)^2 = A^(3 : ℤ) * B^j * (A^(3 : ℤ) * B^j) := by rw [pow_two]
      _ = A^(3 : ℤ) * (B^j * A^(3 : ℤ)) * B^j := by simp [mul_assoc]
      _ = A^(3 : ℤ) * (A^(3 : ℤ) * B^(-j)) * B^j := by rw [hBA3]
      _ = (A^(3 : ℤ) * A^(3 : ℤ)) * (B^(-j) * B^j) := by simp [mul_assoc]
      _ = A^((3 : ℤ) + 3) * B^((-j)+j) := by rw [zpow_add, zpow_add]
      _ = A^(6 : ℤ) * 1 := by rw [neg_add_cancel, zpow_zero]; norm_num
      _ = A^(2 : ℤ) := by rw [mul_one, hA62]
  have hBpow_mem : ∀ n : ℤ, B^n ∈ T := by
    intro n
    have hnmod : B ^ (n % (7 : ℤ)) = B^n := by
      simpa [hBo] using zpow_mod_orderOf B n
    have hnonneg : 0 ≤ n % (7 : ℤ) := Int.emod_nonneg _ (by norm_num)
    have hlt : n % (7 : ℤ) < 7 := Int.emod_lt_of_pos _ (by norm_num)
    interval_cases hr : n % (7 : ℤ)
    · refine ⟨[(0,0)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,1)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,2)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,3)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,4)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,5)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
    · refine ⟨[(0,6)], ?_, ?_⟩ <;> simp [L, hword, ← hnmod]
  have hA2_mem : A^(2 : ℤ) ∈ T := by
    refine ⟨[(2,0)], ?_, ?_⟩
    · simp [L]
    · simp [hword]
  have hsq_mem : ∀ i j : ℤ, (A^i * B^j)^2 ∈ T := by
    intro i j
    have himod : A ^ (i % (4 : ℤ)) = A^i := by
      simpa [hAo] using zpow_mod_orderOf A i
    have hnonneg : 0 ≤ i % (4 : ℤ) := Int.emod_nonneg _ (by norm_num)
    have hlt : i % (4 : ℤ) < 4 := Int.emod_lt_of_pos _ (by norm_num)
    interval_cases hi : i % (4 : ℤ)
    · have hs : (A^i * B^j)^2 = B^(2*j) := by
        rw [← himod]
        simpa [hi] using hsqB j
      simpa [hs] using hBpow_mem (2*j)
    · have hs : (A^i * B^j)^2 = A^(2 : ℤ) := by
        rw [← himod]
        simpa [hi] using hsqA1 j
      simpa [hs] using hA2_mem
    · have hs : (A^i * B^j)^2 = B^(2*j) := by
        rw [← himod]
        simpa [hi] using hsqA2 j
      simpa [hs] using hBpow_mem (2*j)
    · have hs : (A^i * B^j)^2 = A^(2 : ℤ) := by
        rw [← himod]
        simpa [hi] using hsqA3 j
      simpa [hs] using hA2_mem
  have hBsq_word : ∀ r k : ℤ, (2*r) ≡ k [ZMOD (7 : ℤ)] → (B^r)^2 = word [(0,k)] := by
    intro r k hk
    calc
      (B^r)^2 = B^(2*r) := hsqB r
      _ = B^k := by
        rw [zpow_eq_zpow_iff_modEq, hBo]
        exact hk
      _ = word [(0,k)] := by simp [hword]
  have hT_subset_S : T ⊆ S := by
    intro x hx
    rcases hx with ⟨w, hwL, rfl⟩
    rw [hS]
    simp [L] at hwL
    rcases hwL with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · refine ⟨1, ?_⟩
      simp [hword]
    · refine ⟨A, ?_⟩
      simp [hword, pow_two, zpow_two]
    · refine ⟨B^(4 : ℤ), ?_⟩
      exact hBsq_word 4 1 (by norm_num [Int.ModEq])
    · refine ⟨B^(1 : ℤ), ?_⟩
      exact hBsq_word 1 2 (by norm_num [Int.ModEq])
    · refine ⟨B^(5 : ℤ), ?_⟩
      exact hBsq_word 5 3 (by norm_num [Int.ModEq])
    · refine ⟨B^(2 : ℤ), ?_⟩
      exact hBsq_word 2 4 (by norm_num [Int.ModEq])
    · refine ⟨B^(6 : ℤ), ?_⟩
      exact hBsq_word 6 5 (by norm_num [Int.ModEq])
    · refine ⟨B^(3 : ℤ), ?_⟩
      exact hBsq_word 3 6 (by norm_num [Int.ModEq])
  have hS_subset_T : S ⊆ T := by
    intro x hx
    rw [hS] at hx
    rcases hx with ⟨C, hCx⟩
    obtain ⟨w, hCw⟩ := hG C
    obtain ⟨i, j, hw_nf⟩ := hnf_word w
    have hCnf : C = A^i * B^j := hCw.trans hw_nf
    rw [← hCx, hCnf]
    exact hsq_mem i j
  have hST : S = T := Set.Subset.antisymm hS_subset_T hT_subset_S
  have hA2_ne_one : A^(2 : ℤ) ≠ 1 := by
    simpa [zpow_two, pow_two] using hA.2
  have hB_ne : ∀ m n : ℤ, ¬ m ≡ n [ZMOD (7 : ℤ)] → B^m ≠ B^n := by
    intro m n hmn h
    have hmod : m ≡ n [ZMOD (orderOf B : ℤ)] := (zpow_eq_zpow_iff_modEq).mp h
    rw [hBo] at hmod
    exact hmn hmod
  have hA2_ne_B : ∀ k : ℤ, ¬ (2*k) ≡ 0 [ZMOD (7 : ℤ)] → A^(2 : ℤ) ≠ B^k := by
    intro k hk h
    have hA2sq : (A^(2 : ℤ))^2 = 1 := by
      rw [pow_two, ← zpow_add]
      change A^(4 : ℤ) = 1
      rw [zpow_eq_one_iff_modEq, hAo]
      norm_num [Int.ModEq]
    have hBsq : B^(2*k) = 1 := by
      calc
        B^(2*k) = (B^k)^2 := by
          rw [pow_two, ← zpow_add]
          ring_nf
        _ = (A^(2 : ℤ))^2 := by rw [← h]
        _ = 1 := hA2sq
    have hmod : (2*k) ≡ 0 [ZMOD (orderOf B : ℤ)] := by
      rw [← zpow_eq_one_iff_modEq]
      exact hBsq
    rw [hBo] at hmod
    exact hk hmod
  have hw00 : word [(0,0)] = (1 : G) := by simp [hword]
  have hw20 : word [(2,0)] = A^(2 : ℤ) := by simp [hword]
  have hw01 : word [(0,1)] = B := by simp [hword]
  have hw02 : word [(0,2)] = B^(2 : ℤ) := by simp [hword]
  have hw03 : word [(0,3)] = B^(3 : ℤ) := by simp [hword]
  have hw04 : word [(0,4)] = B^(4 : ℤ) := by simp [hword]
  have hw05 : word [(0,5)] = B^(5 : ℤ) := by simp [hword]
  have hw06 : word [(0,6)] = B^(6 : ℤ) := by simp [hword]
  have hT_explicit :
      T = ({1, A^(2 : ℤ), B, B^(2 : ℤ), B^(3 : ℤ), B^(4 : ℤ), B^(5 : ℤ), B^(6 : ℤ)} : Set G) := by
    apply Set.Subset.antisymm
    · intro x hx
      rcases hx with ⟨w, hwL, rfl⟩
      simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff] at hwL
      rcases hwL with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
      · rw [hw00]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or]
      · rw [hw20]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw01]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw02]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw03]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw04]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw05]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · rw [hw06]
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
    · intro x hx
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
      · refine ⟨[(0,0)], ?_, hw00⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or]
      · refine ⟨[(2,0)], ?_, hw20⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,1)], ?_, hw01⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,2)], ?_, hw02⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,3)], ?_, hw03⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,4)], ?_, hw04⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,5)], ?_, hw05⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
      · refine ⟨[(0,6)], ?_, hw06⟩
        simp only [L, Set.mem_insert_iff, Set.mem_singleton_iff, eq_self_iff_true, true_or, or_true]
  have hExplicit_card :
      ({1, A^(2 : ℤ), B, B^(2 : ℤ), B^(3 : ℤ), B^(4 : ℤ), B^(5 : ℤ), B^(6 : ℤ)} : Set G).ncard = 8 := by
    have h1A : (1 : G) ≠ A^(2 : ℤ) := hA2_ne_one.symm
    have h1B1 : (1 : G) ≠ B := by simpa using (hB_ne 1 0 (by norm_num [Int.ModEq])).symm
    have h1B2 : (1 : G) ≠ B^(2 : ℤ) := by simpa using (hB_ne 2 0 (by norm_num [Int.ModEq])).symm
    have h1B3 : (1 : G) ≠ B^(3 : ℤ) := by simpa using (hB_ne 3 0 (by norm_num [Int.ModEq])).symm
    have h1B4 : (1 : G) ≠ B^(4 : ℤ) := by simpa using (hB_ne 4 0 (by norm_num [Int.ModEq])).symm
    have h1B5 : (1 : G) ≠ B^(5 : ℤ) := by simpa using (hB_ne 5 0 (by norm_num [Int.ModEq])).symm
    have h1B6 : (1 : G) ≠ B^(6 : ℤ) := by simpa using (hB_ne 6 0 (by norm_num [Int.ModEq])).symm
    have hA2B1 : A^(2 : ℤ) ≠ B := by simpa using hA2_ne_B 1 (by norm_num [Int.ModEq])
    have hA2B2 : A^(2 : ℤ) ≠ B^(2 : ℤ) := hA2_ne_B 2 (by norm_num [Int.ModEq])
    have hA2B3 : A^(2 : ℤ) ≠ B^(3 : ℤ) := hA2_ne_B 3 (by norm_num [Int.ModEq])
    have hA2B4 : A^(2 : ℤ) ≠ B^(4 : ℤ) := hA2_ne_B 4 (by norm_num [Int.ModEq])
    have hA2B5 : A^(2 : ℤ) ≠ B^(5 : ℤ) := hA2_ne_B 5 (by norm_num [Int.ModEq])
    have hA2B6 : A^(2 : ℤ) ≠ B^(6 : ℤ) := hA2_ne_B 6 (by norm_num [Int.ModEq])
    have hB12 : B ≠ B^(2 : ℤ) := by simpa using hB_ne 1 2 (by norm_num [Int.ModEq])
    have hB13 : B ≠ B^(3 : ℤ) := by simpa using hB_ne 1 3 (by norm_num [Int.ModEq])
    have hB14 : B ≠ B^(4 : ℤ) := by simpa using hB_ne 1 4 (by norm_num [Int.ModEq])
    have hB15 : B ≠ B^(5 : ℤ) := by simpa using hB_ne 1 5 (by norm_num [Int.ModEq])
    have hB16 : B ≠ B^(6 : ℤ) := by simpa using hB_ne 1 6 (by norm_num [Int.ModEq])
    have hB23 : B^(2 : ℤ) ≠ B^(3 : ℤ) := hB_ne 2 3 (by norm_num [Int.ModEq])
    have hB24 : B^(2 : ℤ) ≠ B^(4 : ℤ) := hB_ne 2 4 (by norm_num [Int.ModEq])
    have hB25 : B^(2 : ℤ) ≠ B^(5 : ℤ) := hB_ne 2 5 (by norm_num [Int.ModEq])
    have hB26 : B^(2 : ℤ) ≠ B^(6 : ℤ) := hB_ne 2 6 (by norm_num [Int.ModEq])
    have hB34 : B^(3 : ℤ) ≠ B^(4 : ℤ) := hB_ne 3 4 (by norm_num [Int.ModEq])
    have hB35 : B^(3 : ℤ) ≠ B^(5 : ℤ) := hB_ne 3 5 (by norm_num [Int.ModEq])
    have hB36 : B^(3 : ℤ) ≠ B^(6 : ℤ) := hB_ne 3 6 (by norm_num [Int.ModEq])
    have hB45 : B^(4 : ℤ) ≠ B^(5 : ℤ) := hB_ne 4 5 (by norm_num [Int.ModEq])
    have hB46 : B^(4 : ℤ) ≠ B^(6 : ℤ) := hB_ne 4 6 (by norm_num [Int.ModEq])
    have hB56 : B^(5 : ℤ) ≠ B^(6 : ℤ) := hB_ne 5 6 (by norm_num [Int.ModEq])
    repeat rw [Set.ncard_insert_of_notMem]
    rw [Set.ncard_singleton]
    all_goals simp [h1A, h1B1, h1B2, h1B3, h1B4, h1B5, h1B6,
      hA2B1, hA2B2, hA2B3, hA2B4, hA2B5, hA2B6,
      hB12, hB13, hB14, hB15, hB16, hB23, hB24, hB25, hB26,
      hB34, hB35, hB36, hB45, hB46, hB56]
  constructor
  · rw [hST, hT_explicit]
    exact hExplicit_card
  · exact hST
